# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Test
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Go 1.17.8
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.8
        id: go

      - name: Check out code into the go moudle directory
        uses: actions/checkout@v2

      - name: Install golang-migrate
        uses: |
        curl -L https://github.com/golang-migrate/releasees/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv miarate.linux-amd64 /usr/bin
        which migrate

      - name: Run migrate
        run: make migrateup

      # Runs a single command using the runners shell
      - name: Test
        run: make test